# Adjust this template file for your needs. 
# The orca-base:latest image is build on debian:bookworm-slim 
# With everything basic tooling and setup for claude sandboxing
# For custom claude settings different from the manged settings for sandboxing, we recommend using the settings in your
# project workspace (see https://code.claude.com/docs/en/settings#how-scopes-interact)
FROM orca-base:latest

# Installation of your project specific tooling starts here.
# e.g. :
# USER root
# RUN apt-get update \
#    && apt-get install -y --no-install-recommends \
#        python3 \
#    && rm -rf /var/lib/apt/lists/*
# USER claude